#  ========================[ Format ]===================================

# {ch}: 채널 이름
# {nick}: 시청자 닉네임
# {msg}: 메세지
# {paid}: 후원 금액
# {plat} 플렛폼
# --/채팅/--
채팅:
  이모티콘: "&7(이모티콘)&f"
  익명: "(익명)"
  형식: "&l[ &a{ch}&f ] &r {nick} : {msg} &7- &r&l[ {plat} ]"
# --/후원/--
후원:
  형식: "&l[ &a{ch}&f ] &e{paid}원 &7> &f{nick} &d:: &b{msg} &7- &r&l&6[ 후원 ]"
  타이틀표시: true
  타이틀형식: "&e{paid}&f원 후원!"

플렛폼:
  # --/플렛폼 표시 설정/--
  # color가 true일때 {plat}이 치지직이라면 "치지직"이라는 글자가 초록색으로 표기됩니다.
  채색: true
  # 치지직일 경우 Chzzk으로 표시됨
  영어: false

# ========================[ Event ]===================================

# 후원을 받았을때 그 금액에 설정된 명령어를 실행합니다
# 명령어를 실행하고 싶지 않다면 공백으로 두거나 아예 지워버리면 됩니다.
# 명령어로도 설정 가능 ( /oa 후원 (금액) (명령어) )
# ex) '10000': "kill {player}" -> 1000원을 후원 받으면 kill 명령어가 실행됨
# {player}:플레이어 닉네임
# {user}: 후원자 닉네임
# {msg}: 후원 메세지
# {paid}: 후원 금액
# !- 명령어의 주체는 채널의 주인( 채널을 등록한 플레이어 )입니다 -!
#  - 명령어 앞에 'console:'을 붙이면 명령어 주체를 콘솔로 설정 가능합니다.
#
후원이벤트:
  '금액': '(console:)명령어'
#  '1000': "kill {player}"
#  '2000': "console:say a"
#  '3000': "custom_command"

#  ========================[ Plugin ]===================================

치지직:
  필수-태그:
    활성화: false
    키워드: ''
  필수-타이틀:
    활성화: false
    키워드: ''

platforms:
  - 치지직
  - 유튜브
  - 투네이션
  - 숲
  - 트위치

#========================[ API ]===================================

chzzk:
  client:
    id: '1a6d2335-0a2a-4e75-81c6-1f19b022fa5f'
    secret: 'DcbJtEcmhwHa2-ih9IBV3yMRTRh-OuR_8P739sDPreM'
  # 밑 3개중 택1 (필수 X)
  api:
    accessToken: ''
    refreshToken: ''
  cookie:
    ses: ''
    aut: ''
  naver:
    id: ''
    pw: ''

youtube:
  key: 'AIzaSyB9OU6s_oA_6Hi6hW1zTyW37Rmak33F2aM'

twitch:
  client:
    id: '6gshnlmyln3571aff1ou65tt6m9u6j'
    secret: 'cgckgjb6pltz77qz4mauj14drzvfcn'
  token: ''

soop:
  # 별풍선을 KRW로 변환
  donation-balloon: false

# ========================[ Dev ]===================================

language: 'ko'
debug: false