#  ========================[ Format ]===================================

# {user}: 닉네임
# {msg}: 메세지
# {paid}: 후원 금액
# {plat} 플렛폼
# --/채팅/--
채팅:
  형식: "&f {user} : {msg} &7- &r&l[ {plat} ]"
# --/후원/--
후원:
  형식: "&e{paid}원 &7>&f{user} &d:: &b{msg} &7- &r&l&6[ 후원 ]"
  타이틀표시: true
  타이틀형식: "&e{paid}&f원 후원!"

# --/플렛폼 표시 설정/--
# color가 true일때 {plat}이 치지직이라면 "치지직"이라는 글자가 초록색으로 표기됩니다.
채색: true
# 치직일 경우 Chzzk으로 표시됨
영어플렛폼: false

# ========================[ Event ]===================================

# 후원을 받았을때 그 금액에 설정된 명령어를 실행합니다
# 명령어를 실행하고 싶지 않다면 공백으로 두거나 아예 지워버리면 됩니다.
# 콘솔에서 실행-> 앞에 $ 붙이기
# ex) 10000: "kill {player}" -> 1000원을 후원 받으면 kill 명령어가 실행됨
# {player}::플레이어 닉네임
# {msg} :: 후원 메세지
# {paid} :: 후원 금액
# !- 명령어의 주제는 채널의 주인( 채널을 등록한 플레이어 )입니다 -!
#
후원이벤트:
#  '1000': "kill {player}"
#  '2000': "say a"

#========================[ API ]===================================

chzzk:
  client:
    id: '1a6d2335-0a2a-4e75-81c6-1f19b022fa5f'
    secret: 'DcbJtEcmhwHa2-ih9IBV3yMRTRh-OuR_8P739sDPreM'
  # 밑 3개중 택1
  api:
    accessToken: ''
    refreshToken: ''
  cookie:
    ses: ''
    aut: ''
  naver:
    id: ''
    pw: ''

# ========================[ Dev ]===================================

language: 'ko'
debug: false