name: OnAir
version: ${version}
main: kr.apo2073.onair.OnAir
api-version: '1.20'
authors: [ APO2073 ]
soft-depend: [
  Skript,
  Placeholder
]

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.2.21
  - com.squareup.okhttp3:okhttp:4.9.3
  - org.java-websocket:Java-WebSocket:1.5.2
  - org.jsoup:jsoup:1.15.3
  - io.reactivex.rxjava3:rxjava:3.1.10
  - io.socket:socket.io-client:2.1.1
  - org.seleniumhq.selenium:selenium-java:4.34.0
  - io.github.bonigarcia:webdrivermanager:6.2.0
  - com.google.apis:google-api-services-youtube:v3-rev20230816-2.0.0
  - com.google.http-client:google-http-client-jackson2:1.39.2
  - com.google.api-client:google-api-client:1.33.0
  - com.github.twitch4j:twitch4j:1.25.0

permissions:
  apo.oa.*:
    children:
      apo.oa.channel: true
      apo.oa.donation: true
      apo.oa.admin: true

    apo.oa.channel:
      default: op
    apo.oa.donation:
      default: op
    apo.oa.admin:
      default: op